const products = [
  {
    id: 'phone-1',
    title: 'Smartphone Vision X12',
    category: 'Elektronica',
    price: 799,
    tag: 'Nieuw',
    hero: true,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    description: 'Krachtige smartphone met 5G, OLED-display en driedubbele camera.',
    highlights: ['5G ready', '120Hz OLED', '48MP camera', 'Snellaad oplader inbegrepen'],
  },
  {
    id: 'headphones-1',
    title: 'Noise Cancelling Hoofdtelefoon',
    category: 'Elektronica',
    price: 249,
    tag: 'Bestseller',
    hero: true,
    image: 'https://images.unsplash.com/photo-1512034400317-de97d7d6c3ed?auto=format&fit=crop&w=800&q=80',
    description: 'Draadloos, 30 uur batterij en topklasse noise cancelling.',
    highlights: ['Multipoint bluetooth', 'Snellaad 10 min = 5 uur', 'Inklapbaar design'],
  },
  {
    id: 'lego-1',
    title: 'LEGO® City Brandweerkazerne',
    category: 'Speelgoed',
    price: 89,
    tag: 'Cadeautip',
    hero: true,
    image: 'https://images.unsplash.com/photo-1582719478248-54e9f2be9c02?auto=format&fit=crop&w=800&q=80',
    description: 'Uitgebreide set met voertuigen, minifiguren en veel accessoires.',
    highlights: ['Inclusief 5 minifiguren', 'Vuurweer voertuig', '8+ jaar'],
  },
  {
    id: 'book-1',
    title: 'Thriller: De Nachtwachter',
    category: 'Boeken',
    price: 21,
    tag: 'Nieuw',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=80',
    description: 'Een meeslepende thriller vol onverwachte wendingen.',
    highlights: ['Hardcover', 'Auteur: J. Visser', '320 pagina\'s'],
  },
  {
    id: 'pan-1',
    title: 'Kookpan RVS 24cm',
    category: 'Huis & Tuin',
    price: 59,
    tag: 'Keuze van ons',
    image: 'https://images.unsplash.com/photo-1510626176961-4b37d0b4e904?auto=format&fit=crop&w=800&q=80',
    description: 'Professionele kookpan met glazen deksel en inductie geschikt.',
    highlights: ['Geschikt voor inductie', 'Vaatwasserbestendig', '10 jaar garantie'],
  },
  {
    id: 'game-1',
    title: 'Console Game: Galaxy Quest',
    category: 'Gaming',
    price: 69,
    tag: 'Pre-order',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    description: 'Episodisch avontuur in 4K met co-op en crossplay.',
    highlights: ['4K HDR', 'Online co-op', 'Release: binnenkort'],
  },
  {
    id: 'fashion-1',
    title: 'Comfort Fit Hoodie',
    category: 'Mode',
    price: 49,
    tag: 'Limited',
    image: 'https://images.unsplash.com/photo-1542293787938-4d4f0f9d6835?auto=format&fit=crop&w=800&q=80',
    description: 'Zachte fleece hoodie met ruime pasvorm en kangoeroezak.',
    highlights: ['Unisex', 'Verkrijgbaar in 5 kleuren', 'Machinewasbaar'],
  },
  {
    id: 'smart-home-1',
    title: 'Slimme Speaker Mini',
    category: 'Elektronica',
    price: 59,
    tag: 'Aanbieding',
    image: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=800&q=80',
    description: 'Stembediening voor muziek, weer en slimme apparaten.',
    highlights: ['Google Assistant', 'Bluetooth en WiFi', 'Compact design'],
  },
];

const categories = [
  {
    name: 'Elektronica',
    description: 'Telefoons, audio, smart home en meer.',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Speelgoed',
    description: 'De leukste cadeaus voor alle leeftijden.',
    image: 'https://images.unsplash.com/photo-1551963831-b3b1ca40c98e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Boeken',
    description: 'Nieuwe bestsellers en tijdloze klassiekers.',
    image: 'https://images.unsplash.com/photo-1457694587812-e8bf29a43845?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Huis & Tuin',
    description: 'Alles voor koken, klussen en wonen.',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Gaming',
    description: 'Consoles, accessoires en de nieuwste titels.',
    image: 'https://images.unsplash.com/photo-1523968044756-39c9b6c717a5?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mode',
    description: 'Basics en trends voor elke stijl.',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80',
  },
];
